# Generated by Django 5.1.1 on 2024-11-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_locatin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='locatin',
            new_name='location',
        ),
    ]
