# Generated by Django 5.1 on 2024-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
